version: '3'

services:
  web:
    build: .
    container_name: fast_api_web
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo: